#include "sql.h"

const char *SQL_schema = "CREATE TABLE SCHEMA ( version INTEGER ); INSERT INTO \"SCHEMA\" VALUES(" DB_VERSION ");";

const char *dailyObsSchema = "CREATE TABLE dailyObs ( time INTEGER PRIMARY KEY,"
                     "insideTemp      FLOAT,"
                     "insideHumidity  FLOAT,"
                     "outsideTemp     FLOAT,"
                     "outsideHumidity FLOAT,"
                     "windSpeed       FLOAT,"
                     "windDirection   FLOAT,"
                     "windGust        FLOAT,"
                     "windGustDir     FLOAT,"
                     "rainRate        FLOAT,"
                     "rain24Hour      FLOAT,"
                     "dailyRain       FLOAT,"
                     "dailyET         FLOAT,"
                     "instantRain     FLOAT,"
                     "UV              FLOAT,"
                     "solarRadiation  FLOAT,"
                     "solarRadiationPercent  FLOAT,"
                     "barometricTrend TREND,"
                     "rawBarometer    FLOAT,"
                     "SLP             FLOAT,"
                     "altimeter       FLOAT,"
                     "dewPoint        FLOAT,"
                     "heatIndex       FLOAT,"
                     "humidex         FLOAT,"
                     "windChill       FLOAT,"
                     "apparentTemp    FLOAT,"
                     "cloudHeight     INT,"
                     "extraTemp1      FLOAT,"
                     "extraTemp2      FLOAT,"
                     "extraTemp3      FLOAT,"
                     "extraTemp4      FLOAT,"
                     "extraTemp5      FLOAT,"
                     "extraTemp6      FLOAT,"
                     "extraTemp7      FLOAT,"
                     "extraTemp8      FLOAT,"
                     "extraHumidity1  FLOAT,"
                     "extraHumidity2  FLOAT,"
                     "extraHumidity3  FLOAT,"
                     "extraHumidity4  FLOAT,"
                     "extraHumidity5  FLOAT,"
                     "extraHumidity6  FLOAT,"
                     "extraHumidity7  FLOAT,"
                     "extraHumidity8  FLOAT,"
                     "soilTemp1       FLOAT,"
                     "soilTemp2       FLOAT,"
                     "soilTemp3       FLOAT,"
                     "soilTemp4       FLOAT,"
                     "soilTemp5       FLOAT,"
                     "soilTemp6       FLOAT,"
                     "soilTemp7       FLOAT,"
                     "soilTemp8       FLOAT,"
                     "soilMoisture1   FLOAT,"
                     "soilMoisture2   FLOAT,"
                     "soilMoisture3   FLOAT,"
                     "soilMoisture4   FLOAT,"
                     "soilMoisture5   FLOAT,"
                     "soilMoisture6   FLOAT,"
                     "soilMoisture7   FLOAT,"
                     "soilMoisture8   FLOAT,"
                     "leafTemp1       FLOAT,"
                     "leafTemp2       FLOAT,"
                     "leafTemp3       FLOAT,"
                     "leafTemp4       FLOAT,"
                     "leafTemp5       FLOAT,"
                     "leafTemp6       FLOAT,"
                     "leafTemp7       FLOAT,"
                     "leafTemp8       FLOAT,"
                     "leafWetness1    FLOAT,"
                     "leafWetness2    FLOAT,"
                     "leafWetness3    FLOAT,"
                     "leafWetness4    FLOAT,"
                     "leafWetness5    FLOAT,"
                     "leafWetness6    FLOAT,"
                     "leafWetness7    FLOAT,"
                     "leafWetness8    FLOAT );";

const char *hourlySummarySchema = 
                     "CREATE TABLE hourlySummary ( time INTEGER PRIMARY KEY,"
                     "insideTempMin           FLOAT,"
                     "insideTempMinTime       TIME,"
                     "insideTempMax           FLOAT,"
                     "insideTempMaxTime       TIME,"
                     "insideTempAvg           FLOAT,"
                     "insideHumidityMin           FLOAT,"
                     "insideHumidityMinTime       TIME,"
                     "insideHumidityMax           FLOAT,"
                     "insideHumidityMaxTime       TIME,"
                     "insideHumidityAvg           FLOAT,"
                     "outsideTempMin           FLOAT,"
                     "outsideTempMinTime       TIME,"
                     "outsideTempMax           FLOAT,"
                     "outsideTempMaxTime       TIME,"
                     "outsideTempAvg           FLOAT,"
                     "outsideHumidityMin           FLOAT,"
                     "outsideHumidityMinTime       TIME,"
                     "outsideHumidityMax           FLOAT,"
                     "outsideHumidityMaxTime       TIME,"
                     "outsideHumidityAvg           FLOAT,"
                     "windSpeedMin           FLOAT,"
                     "windSpeedMinTime       TIME,"
                     "windSpeedMax           FLOAT,"
                     "windSpeedMaxTime       TIME,"
                     "windSpeedAvg           FLOAT,"
                     "windGustMin           FLOAT,"
                     "windGustMinTime       TIME,"
                     "windGustMax           FLOAT,"
                     "windGustMaxTime       TIME,"
                     "windGustAvg           FLOAT,"
                     "windDirectionAvg           FLOAT,"
                     "windGustDirAvg        FLOAT,"
                     "rainRateMin           FLOAT,"
                     "rainRateMinTime       TIME,"
                     "rainRateMax           FLOAT,"
                     "rainRateMaxTime       TIME,"
                     "rainRateAvg           FLOAT,"
                     "rain24HourMin         FLOAT,"
                     "rain24HourMinTime     TIME,"
                     "rain24HourMax         FLOAT,"
                     "rain24HourMaxTime     TIME,"
                     "rain24HourAvg         FLOAT,"
                     "dailyRain            FLOAT,"
                     "dailyET              FLOAT,"
                     "instantRainMax       FLOAT," 
                     "instantRainMaxTime   TIME,"
                     "UVMin           FLOAT,"
                     "UVMinTime       TIME,"
                     "UVMax           FLOAT,"
                     "UVMaxTime       TIME,"
                     "UVAvg           FLOAT,"
                     "solarRadiationMin           FLOAT,"
                     "solarRadiationMinTime       TIME,"
                     "solarRadiationMax           FLOAT,"
                     "solarRadiationMaxTime       TIME,"
                     "solarRadiationAvg           FLOAT,"
                     "solarRadiationPercentMin           FLOAT,"
                     "solarRadiationPercentMinTime       TIME,"
                     "solarRadiationPercentMax           FLOAT,"
                     "solarRadiationPercentMaxTime       TIME,"
                     "solarRadiationPercentAvg           FLOAT,"
                     "rawBarometerMin           FLOAT,"
                     "rawBarometerMinTime       TIME,"
                     "rawBarometerMax           FLOAT,"
                     "rawBarometerMaxTime       TIME,"
                     "rawBarometerAvg           FLOAT,"
                     "SLPMin           FLOAT,"
                     "SLPMinTime       TIME,"
                     "SLPMax           FLOAT,"
                     "SLPMaxTime       TIME,"
                     "SLPAvg           FLOAT,"
                     "altimeterMin           FLOAT,"
                     "altimeterMinTime       TIME,"
                     "altimeterMax           FLOAT,"
                     "altimeterMaxTime       TIME,"
                     "altimeterAvg           FLOAT,"
                     "heatIndexMin           FLOAT,"
                     "heatIndexMinTime       TIME,"
                     "heatIndexMax           FLOAT,"
                     "heatIndexMaxTime       TIME,"
                     "heatIndexAvg           FLOAT,"
                     "humidexMin           FLOAT,"
                     "humidexMinTime       TIME,"
                     "humidexMax           FLOAT,"
                     "humidexMaxTime       TIME,"
                     "humidexAvg           FLOAT,"
                     "windChillMin           FLOAT,"
                     "windChillMinTime       TIME,"
                     "windChillMax           FLOAT,"
                     "windChillMaxTime       TIME,"
                     "windChillAvg           FLOAT,"
                     "apparentTempMin           FLOAT,"
                     "apparentTempMinTime       TIME,"
                     "apparentTempMax           FLOAT,"
                     "apparentTempMaxTime       TIME,"
                     "apparentTempAvg           FLOAT,"
                     "cloudHeightMin           FLOAT,"
                     "cloudHeightMinTime       TIME,"
                     "cloudHeightMax           FLOAT,"
                     "cloudHeightMaxTime       TIME,"
                     "cloudHeightAvg           FLOAT,"
                     "dewPointMin           FLOAT,"
                     "dewPointMinTime       TIME,"
                     "dewPointMax           FLOAT,"
                     "dewPointMaxTime       TIME,"
                     "dewPointAvg           FLOAT,"
                     "extraTemp1Min           FLOAT,"
                     "extraTemp1MinTime       TIME,"
                     "extraTemp1Max           FLOAT,"
                     "extraTemp1MaxTime       TIME,"
                     "extraTemp1Avg           FLOAT,"
                     "extraTemp2Min           FLOAT,"
                     "extraTemp2MinTime       TIME,"
                     "extraTemp2Max           FLOAT,"
                     "extraTemp2MaxTime       TIME,"
                     "extraTemp2Avg           FLOAT,"
                     "extraTemp3Min           FLOAT,"
                     "extraTemp3MinTime       TIME,"
                     "extraTemp3Max           FLOAT,"
                     "extraTemp3MaxTime       TIME,"
                     "extraTemp3Avg           FLOAT,"
                     "extraTemp4Min           FLOAT,"
                     "extraTemp4MinTime       TIME,"
                     "extraTemp4Max           FLOAT,"
                     "extraTemp4MaxTime       TIME,"
                     "extraTemp4Avg           FLOAT,"
                     "extraTemp5Min           FLOAT,"
                     "extraTemp5MinTime       TIME,"
                     "extraTemp5Max           FLOAT,"
                     "extraTemp5MaxTime       TIME,"
                     "extraTemp5Avg           FLOAT,"
                     "extraTemp6Min           FLOAT,"
                     "extraTemp6MinTime       TIME,"
                     "extraTemp6Max           FLOAT,"
                     "extraTemp6MaxTime       TIME,"
                     "extraTemp6Avg           FLOAT,"
                     "extraTemp7Min           FLOAT,"
                     "extraTemp7MinTime       TIME,"
                     "extraTemp7Max           FLOAT,"
                     "extraTemp7MaxTime       TIME,"
                     "extraTemp7Avg           FLOAT,"
                     "extraTemp8Min           FLOAT,"
                     "extraTemp8MinTime       TIME,"
                     "extraTemp8Max           FLOAT,"
                     "extraTemp8MaxTime       TIME,"
                     "extraTemp8Avg           FLOAT,"
                     "extraHumidity1Min           FLOAT,"
                     "extraHumidity1MinTime       TIME,"
                     "extraHumidity1Max           FLOAT,"
                     "extraHumidity1MaxTime       TIME,"
                     "extraHumidity1Avg           FLOAT,"
                     "extraHumidity2Min           FLOAT,"
                     "extraHumidity2MinTime       TIME,"
                     "extraHumidity2Max           FLOAT,"
                     "extraHumidity2MaxTime       TIME,"
                     "extraHumidity2Avg           FLOAT,"
                     "extraHumidity3Min           FLOAT,"
                     "extraHumidity3MinTime       TIME,"
                     "extraHumidity3Max           FLOAT,"
                     "extraHumidity3MaxTime       TIME,"
                     "extraHumidity3Avg           FLOAT,"
                     "extraHumidity4Min           FLOAT,"
                     "extraHumidity4MinTime       TIME,"
                     "extraHumidity4Max           FLOAT,"
                     "extraHumidity4MaxTime       TIME,"
                     "extraHumidity4Avg           FLOAT,"
                     "extraHumidity5Min           FLOAT,"
                     "extraHumidity5MinTime       TIME,"
                     "extraHumidity5Max           FLOAT,"
                     "extraHumidity5MaxTime       TIME,"
                     "extraHumidity5Avg           FLOAT,"
                     "extraHumidity6Min           FLOAT,"
                     "extraHumidity6MinTime       TIME,"
                     "extraHumidity6Max           FLOAT,"
                     "extraHumidity6MaxTime       TIME,"
                     "extraHumidity6Avg           FLOAT,"
                     "extraHumidity7Min           FLOAT,"
                     "extraHumidity7MinTime       TIME,"
                     "extraHumidity7Max           FLOAT,"
                     "extraHumidity7MaxTime       TIME,"
                     "extraHumidity7Avg           FLOAT,"
                     "extraHumidity8Min           FLOAT,"
                     "extraHumidity8MinTime       TIME,"
                     "extraHumidity8Max           FLOAT,"
                     "extraHumidity8MaxTime       TIME,"
                     "extraHumidity8Avg           FLOAT,"
                     "soilTemp1Min           FLOAT,"
                     "soilTemp1MinTime       TIME,"
                     "soilTemp1Max           FLOAT,"
                     "soilTemp1MaxTime       TIME,"
                     "soilTemp1Avg           FLOAT,"
                     "soilTemp2Min           FLOAT,"
                     "soilTemp2MinTime       TIME,"
                     "soilTemp2Max           FLOAT,"
                     "soilTemp2MaxTime       TIME,"
                     "soilTemp2Avg           FLOAT,"
                     "soilTemp3Min           FLOAT,"
                     "soilTemp3MinTime       TIME,"
                     "soilTemp3Max           FLOAT,"
                     "soilTemp3MaxTime       TIME,"
                     "soilTemp3Avg           FLOAT,"
                     "soilTemp4Min           FLOAT,"
                     "soilTemp4MinTime       TIME,"
                     "soilTemp4Max           FLOAT,"
                     "soilTemp4MaxTime       TIME,"
                     "soilTemp4Avg           FLOAT,"
                     "soilTemp5Min           FLOAT,"
                     "soilTemp5MinTime       TIME,"
                     "soilTemp5Max           FLOAT,"
                     "soilTemp5MaxTime       TIME,"
                     "soilTemp5Avg           FLOAT,"
                     "soilTemp6Min           FLOAT,"
                     "soilTemp6MinTime       TIME,"
                     "soilTemp6Max           FLOAT,"
                     "soilTemp6MaxTime       TIME,"
                     "soilTemp6Avg           FLOAT,"
                     "soilTemp7Min           FLOAT,"
                     "soilTemp7MinTime       TIME,"
                     "soilTemp7Max           FLOAT,"
                     "soilTemp7MaxTime       TIME,"
                     "soilTemp7Avg           FLOAT,"
                     "soilTemp8Min           FLOAT,"
                     "soilTemp8MinTime       TIME,"
                     "soilTemp8Max           FLOAT,"
                     "soilTemp8MaxTime       TIME,"
                     "soilTemp8Avg           FLOAT,"
                     "soilMoisture1Min           FLOAT,"
                     "soilMoisture1MinTime       TIME,"
                     "soilMoisture1Max           FLOAT,"
                     "soilMoisture1MaxTime       TIME,"
                     "soilMoisture1Avg           FLOAT,"
                     "soilMoisture2Min           FLOAT,"
                     "soilMoisture2MinTime       TIME,"
                     "soilMoisture2Max           FLOAT,"
                     "soilMoisture2MaxTime       TIME,"
                     "soilMoisture2Avg           FLOAT,"
                     "soilMoisture3Min           FLOAT,"
                     "soilMoisture3MinTime       TIME,"
                     "soilMoisture3Max           FLOAT,"
                     "soilMoisture3MaxTime       TIME,"
                     "soilMoisture3Avg           FLOAT,"
                     "soilMoisture4Min           FLOAT,"
                     "soilMoisture4MinTime       TIME,"
                     "soilMoisture4Max           FLOAT,"
                     "soilMoisture4MaxTime       TIME,"
                     "soilMoisture4Avg           FLOAT,"
                     "soilMoisture5Min           FLOAT,"
                     "soilMoisture5MinTime       TIME,"
                     "soilMoisture5Max           FLOAT,"
                     "soilMoisture5MaxTime       TIME,"
                     "soilMoisture5Avg           FLOAT,"
                     "soilMoisture6Min           FLOAT,"
                     "soilMoisture6MinTime       TIME,"
                     "soilMoisture6Max           FLOAT,"
                     "soilMoisture6MaxTime       TIME,"
                     "soilMoisture6Avg           FLOAT,"
                     "soilMoisture7Min           FLOAT,"
                     "soilMoisture7MinTime       TIME,"
                     "soilMoisture7Max           FLOAT,"
                     "soilMoisture7MaxTime       TIME,"
                     "soilMoisture7Avg           FLOAT,"
                     "soilMoisture8Min           FLOAT,"
                     "soilMoisture8MinTime       TIME,"
                     "soilMoisture8Max           FLOAT,"
                     "soilMoisture8MaxTime       TIME,"
                     "soilMoisture8Avg           FLOAT,"
                     "leafTemperature1Min           FLOAT,"
                     "leafTemperature1MinTime       TIME,"
                     "leafTemperature1Max           FLOAT,"
                     "leafTemperature1MaxTime       TIME,"
                     "leafTemperature1Avg           FLOAT,"
                     "leafTemperature2Min           FLOAT,"
                     "leafTemperature2MinTime       TIME,"
                     "leafTemperature2Max           FLOAT,"
                     "leafTemperature2MaxTime       TIME,"
                     "leafTemperature2Avg           FLOAT,"
                     "leafTemperature3Min           FLOAT,"
                     "leafTemperature3MinTime       TIME,"
                     "leafTemperature3Max           FLOAT,"
                     "leafTemperature3MaxTime       TIME,"
                     "leafTemperature3Avg           FLOAT,"
                     "leafTemperature4Min           FLOAT,"
                     "leafTemperature4MinTime       TIME,"
                     "leafTemperature4Max           FLOAT,"
                     "leafTemperature4MaxTime       TIME,"
                     "leafTemperature4Avg           FLOAT,"
                     "leafTemperature5Min           FLOAT,"
                     "leafTemperature5MinTime       TIME,"
                     "leafTemperature5Max           FLOAT,"
                     "leafTemperature5MaxTime       TIME,"
                     "leafTemperature5Avg           FLOAT,"
                     "leafTemperature6Min           FLOAT,"
                     "leafTemperature6MinTime       TIME,"
                     "leafTemperature6Max           FLOAT,"
                     "leafTemperature6MaxTime       TIME,"
                     "leafTemperature6Avg           FLOAT,"
                     "leafTemperature7Min           FLOAT,"
                     "leafTemperature7MinTime       TIME,"
                     "leafTemperature7Max           FLOAT,"
                     "leafTemperature7MaxTime       TIME,"
                     "leafTemperature7Avg           FLOAT,"
                     "leafTemperature8Min           FLOAT,"
                     "leafTemperature8MinTime       TIME,"
                     "leafTemperature8Max           FLOAT,"
                     "leafTemperature8MaxTime       TIME,"
                     "leafTemperature8Avg           FLOAT,"
                     "leafWetness1Min           FLOAT,"
                     "leafWetness1MinTime       TIME,"
                     "leafWetness1Max           FLOAT,"
                     "leafWetness1MaxTime       TIME,"
                     "leafWetness1Avg           FLOAT,"
                     "leafWetness2Min           FLOAT,"
                     "leafWetness2MinTime       TIME,"
                     "leafWetness2Max           FLOAT,"
                     "leafWetness2MaxTime       TIME,"
                     "leafWetness2Avg           FLOAT,"
                     "leafWetness3Min           FLOAT,"
                     "leafWetness3MinTime       TIME,"
                     "leafWetness3Max           FLOAT,"
                     "leafWetness3MaxTime       TIME,"
                     "leafWetness3Avg           FLOAT,"
                     "leafWetness4Min           FLOAT,"
                     "leafWetness4MinTime       TIME,"
                     "leafWetness4Max           FLOAT,"
                     "leafWetness4MaxTime       TIME,"
                     "leafWetness4Avg           FLOAT,"
                     "leafWetness5Min           FLOAT,"
                     "leafWetness5MinTime       TIME,"
                     "leafWetness5Max           FLOAT,"
                     "leafWetness5MaxTime       TIME,"
                     "leafWetness5Avg           FLOAT,"
                     "leafWetness6Min           FLOAT,"
                     "leafWetness6MinTime       TIME,"
                     "leafWetness6Max           FLOAT,"
                     "leafWetness6MaxTime       TIME,"
                     "leafWetness6Avg           FLOAT,"
                     "leafWetness7Min           FLOAT,"
                     "leafWetness7MinTime       TIME,"
                     "leafWetness7Max           FLOAT,"
                     "leafWetness7MaxTime       TIME,"
                     "leafWetness7Avg           FLOAT,"
                     "leafWetness8Min           FLOAT,"
                     "leafWetness8MinTime       TIME,"
                     "leafWetness8Max           FLOAT,"
                     "leafWetness8MaxTime       TIME,"
                     "leafWetness8Avg           FLOAT );";

const char *windSchema = "create table windData  ( time INTEGEER PRIMARY KEY,"
                   "speed FLOAT,"
                   "dirSin FLOAT,"
                   "dirCos FLOAT);";

const char *rainSchema = "create table rainData  ( time INTEGEER PRIMARY KEY,"
                   "amount FLOAT);";

const char *dailySummarySchema = 
                     "CREATE TABLE dailySummary ( time INTEGER PRIMARY KEY,"
                     "insideTempMin           FLOAT,"
                     "insideTempMinTime       TIME,"
                     "insideTempMax           FLOAT,"
                     "insideTempMaxTime       TIME,"
                     "insideTempAvg           FLOAT,"
                     "insideHumidityMin           FLOAT,"
                     "insideHumidityMinTime       TIME,"
                     "insideHumidityMax           FLOAT,"
                     "insideHumidityMaxTime       TIME,"
                     "insideHumidityAvg           FLOAT,"
                     "outsideTempMin           FLOAT,"
                     "outsideTempMinTime       TIME,"
                     "outsideTempMax           FLOAT,"
                     "outsideTempMaxTime       TIME,"
                     "outsideTempAvg           FLOAT,"
                     "outsideHumidityMin           FLOAT,"
                     "outsideHumidityMinTime       TIME,"
                     "outsideHumidityMax           FLOAT,"
                     "outsideHumidityMaxTime       TIME,"
                     "outsideHumidityAvg           FLOAT,"
                     "windSpeedMin           FLOAT,"
                     "windSpeedMinTime       TIME,"
                     "windSpeedMax           FLOAT,"
                     "windSpeedMaxTime       TIME,"
                     "windSpeedAvg           FLOAT,"
                     "windGustMin           FLOAT,"
                     "windGustMinTime       TIME,"
                     "windGustMax           FLOAT,"
                     "windGustMaxTime       TIME,"
                     "windGustAvg           FLOAT,"
                     "windDirectionAvg           FLOAT,"
                     "windGustDirAvg        FLOAT,"
                     "rainRateMin           FLOAT,"
                     "rainRateMinTime       TIME,"
                     "rainRateMax           FLOAT,"
                     "rainRateMaxTime       TIME,"
                     "rainRateAvg           FLOAT,"
                     "rain24HourMin         FLOAT,"
                     "rain24HourMinTime     TIME,"
                     "rain24HourMax         FLOAT,"
                     "rain24HourMaxTime     TIME,"
                     "rain24HourAvg         FLOAT,"
                     "instantRainMax       FLOAT," 
                     "instantRainMaxTime   TIME,"
                     "dailyRain            FLOAT,"
                     "dailyET              FLOAT,"
                     "UVMin           FLOAT,"
                     "UVMinTime       TIME,"
                     "UVMax           FLOAT,"
                     "UVMaxTime       TIME,"
                     "UVAvg           FLOAT,"
                     "solarRadiationMin           FLOAT,"
                     "solarRadiationMinTime       TIME,"
                     "solarRadiationMax           FLOAT,"
                     "solarRadiationMaxTime       TIME,"
                     "solarRadiationAvg           FLOAT,"
                     "solarRadiationPercentMin           FLOAT,"
                     "solarRadiationPercentMinTime       TIME,"
                     "solarRadiationPercentMax           FLOAT,"
                     "solarRadiationPercentMaxTime       TIME,"
                     "solarRadiationPercentAvg           FLOAT,"
                     "rawBarometerMin           FLOAT,"
                     "rawBarometerMinTime       TIME,"
                     "rawBarometerMax           FLOAT,"
                     "rawBarometerMaxTime       TIME,"
                     "rawBarometerAvg           FLOAT,"
                     "SLPMin           FLOAT,"
                     "SLPMinTime       TIME,"
                     "SLPMax           FLOAT,"
                     "SLPMaxTime       TIME,"
                     "SLPAvg           FLOAT,"
                     "altimeterMin           FLOAT,"
                     "altimeterMinTime       TIME,"
                     "altimeterMax           FLOAT,"
                     "altimeterMaxTime       TIME,"
                     "altimeterAvg           FLOAT,"
                     "heatIndexMin           FLOAT,"
                     "heatIndexMinTime       TIME,"
                     "heatIndexMax           FLOAT,"
                     "heatIndexMaxTime       TIME,"
                     "heatIndexAvg           FLOAT,"
                     "humidexMin           FLOAT,"
                     "humidexMinTime       TIME,"
                     "humidexMax           FLOAT,"
                     "humidexMaxTime       TIME,"
                     "humidexAvg           FLOAT,"
                     "windChillMin           FLOAT,"
                     "windChillMinTime       TIME,"
                     "windChillMax           FLOAT,"
                     "windChillMaxTime       TIME,"
                     "windChillAvg           FLOAT,"
                     "apparentTempMin           FLOAT,"
                     "apparentTempMinTime       TIME,"
                     "apparentTempMax           FLOAT,"
                     "apparentTempMaxTime       TIME,"
                     "apparentTempAvg           FLOAT,"
                     "cloudHeightMin           FLOAT,"
                     "cloudHeightMinTime       TIME,"
                     "cloudHeightMax           FLOAT,"
                     "cloudHeightMaxTime       TIME,"
                     "cloudHeightAvg           FLOAT,"
                     "dewPointMin           FLOAT,"
                     "dewPointMinTime       TIME,"
                     "dewPointMax           FLOAT,"
                     "dewPointMaxTime       TIME,"
                     "dewPointAvg           FLOAT,"
                     "extraTemp1Min           FLOAT,"
                     "extraTemp1MinTime       TIME,"
                     "extraTemp1Max           FLOAT,"
                     "extraTemp1MaxTime       TIME,"
                     "extraTemp1Avg           FLOAT,"
                     "extraTemp2Min           FLOAT,"
                     "extraTemp2MinTime       TIME,"
                     "extraTemp2Max           FLOAT,"
                     "extraTemp2MaxTime       TIME,"
                     "extraTemp2Avg           FLOAT,"
                     "extraTemp3Min           FLOAT,"
                     "extraTemp3MinTime       TIME,"
                     "extraTemp3Max           FLOAT,"
                     "extraTemp3MaxTime       TIME,"
                     "extraTemp3Avg           FLOAT,"
                     "extraTemp4Min           FLOAT,"
                     "extraTemp4MinTime       TIME,"
                     "extraTemp4Max           FLOAT,"
                     "extraTemp4MaxTime       TIME,"
                     "extraTemp4Avg           FLOAT,"
                     "extraTemp5Min           FLOAT,"
                     "extraTemp5MinTime       TIME,"
                     "extraTemp5Max           FLOAT,"
                     "extraTemp5MaxTime       TIME,"
                     "extraTemp5Avg           FLOAT,"
                     "extraTemp6Min           FLOAT,"
                     "extraTemp6MinTime       TIME,"
                     "extraTemp6Max           FLOAT,"
                     "extraTemp6MaxTime       TIME,"
                     "extraTemp6Avg           FLOAT,"
                     "extraTemp7Min           FLOAT,"
                     "extraTemp7MinTime       TIME,"
                     "extraTemp7Max           FLOAT,"
                     "extraTemp7MaxTime       TIME,"
                     "extraTemp7Avg           FLOAT,"
                     "extraTemp8Min           FLOAT,"
                     "extraTemp8MinTime       TIME,"
                     "extraTemp8Max           FLOAT,"
                     "extraTemp8MaxTime       TIME,"
                     "extraTemp8Avg           FLOAT,"
                     "extraHumidity1Min           FLOAT,"
                     "extraHumidity1MinTime       TIME,"
                     "extraHumidity1Max           FLOAT,"
                     "extraHumidity1MaxTime       TIME,"
                     "extraHumidity1Avg           FLOAT,"
                     "extraHumidity2Min           FLOAT,"
                     "extraHumidity2MinTime       TIME,"
                     "extraHumidity2Max           FLOAT,"
                     "extraHumidity2MaxTime       TIME,"
                     "extraHumidity2Avg           FLOAT,"
                     "extraHumidity3Min           FLOAT,"
                     "extraHumidity3MinTime       TIME,"
                     "extraHumidity3Max           FLOAT,"
                     "extraHumidity3MaxTime       TIME,"
                     "extraHumidity3Avg           FLOAT,"
                     "extraHumidity4Min           FLOAT,"
                     "extraHumidity4MinTime       TIME,"
                     "extraHumidity4Max           FLOAT,"
                     "extraHumidity4MaxTime       TIME,"
                     "extraHumidity4Avg           FLOAT,"
                     "extraHumidity5Min           FLOAT,"
                     "extraHumidity5MinTime       TIME,"
                     "extraHumidity5Max           FLOAT,"
                     "extraHumidity5MaxTime       TIME,"
                     "extraHumidity5Avg           FLOAT,"
                     "extraHumidity6Min           FLOAT,"
                     "extraHumidity6MinTime       TIME,"
                     "extraHumidity6Max           FLOAT,"
                     "extraHumidity6MaxTime       TIME,"
                     "extraHumidity6Avg           FLOAT,"
                     "extraHumidity7Min           FLOAT,"
                     "extraHumidity7MinTime       TIME,"
                     "extraHumidity7Max           FLOAT,"
                     "extraHumidity7MaxTime       TIME,"
                     "extraHumidity7Avg           FLOAT,"
                     "extraHumidity8Min           FLOAT,"
                     "extraHumidity8MinTime       TIME,"
                     "extraHumidity8Max           FLOAT,"
                     "extraHumidity8MaxTime       TIME,"
                     "extraHumidity8Avg           FLOAT,"
                     "soilTemp1Min           FLOAT,"
                     "soilTemp1MinTime       TIME,"
                     "soilTemp1Max           FLOAT,"
                     "soilTemp1MaxTime       TIME,"
                     "soilTemp1Avg           FLOAT,"
                     "soilTemp2Min           FLOAT,"
                     "soilTemp2MinTime       TIME,"
                     "soilTemp2Max           FLOAT,"
                     "soilTemp2MaxTime       TIME,"
                     "soilTemp2Avg           FLOAT,"
                     "soilTemp3Min           FLOAT,"
                     "soilTemp3MinTime       TIME,"
                     "soilTemp3Max           FLOAT,"
                     "soilTemp3MaxTime       TIME,"
                     "soilTemp3Avg           FLOAT,"
                     "soilTemp4Min           FLOAT,"
                     "soilTemp4MinTime       TIME,"
                     "soilTemp4Max           FLOAT,"
                     "soilTemp4MaxTime       TIME,"
                     "soilTemp4Avg           FLOAT,"
                     "soilTemp5Min           FLOAT,"
                     "soilTemp5MinTime       TIME,"
                     "soilTemp5Max           FLOAT,"
                     "soilTemp5MaxTime       TIME,"
                     "soilTemp5Avg           FLOAT,"
                     "soilTemp6Min           FLOAT,"
                     "soilTemp6MinTime       TIME,"
                     "soilTemp6Max           FLOAT,"
                     "soilTemp6MaxTime       TIME,"
                     "soilTemp6Avg           FLOAT,"
                     "soilTemp7Min           FLOAT,"
                     "soilTemp7MinTime       TIME,"
                     "soilTemp7Max           FLOAT,"
                     "soilTemp7MaxTime       TIME,"
                     "soilTemp7Avg           FLOAT,"
                     "soilTemp8Min           FLOAT,"
                     "soilTemp8MinTime       TIME,"
                     "soilTemp8Max           FLOAT,"
                     "soilTemp8MaxTime       TIME,"
                     "soilTemp8Avg           FLOAT,"
                     "soilMoisture1Min           FLOAT,"
                     "soilMoisture1MinTime       TIME,"
                     "soilMoisture1Max           FLOAT,"
                     "soilMoisture1MaxTime       TIME,"
                     "soilMoisture1Avg           FLOAT,"
                     "soilMoisture2Min           FLOAT,"
                     "soilMoisture2MinTime       TIME,"
                     "soilMoisture2Max           FLOAT,"
                     "soilMoisture2MaxTime       TIME,"
                     "soilMoisture2Avg           FLOAT,"
                     "soilMoisture3Min           FLOAT,"
                     "soilMoisture3MinTime       TIME,"
                     "soilMoisture3Max           FLOAT,"
                     "soilMoisture3MaxTime       TIME,"
                     "soilMoisture3Avg           FLOAT,"
                     "soilMoisture4Min           FLOAT,"
                     "soilMoisture4MinTime       TIME,"
                     "soilMoisture4Max           FLOAT,"
                     "soilMoisture4MaxTime       TIME,"
                     "soilMoisture4Avg           FLOAT,"
                     "soilMoisture5Min           FLOAT,"
                     "soilMoisture5MinTime       TIME,"
                     "soilMoisture5Max           FLOAT,"
                     "soilMoisture5MaxTime       TIME,"
                     "soilMoisture5Avg           FLOAT,"
                     "soilMoisture6Min           FLOAT,"
                     "soilMoisture6MinTime       TIME,"
                     "soilMoisture6Max           FLOAT,"
                     "soilMoisture6MaxTime       TIME,"
                     "soilMoisture6Avg           FLOAT,"
                     "soilMoisture7Min           FLOAT,"
                     "soilMoisture7MinTime       TIME,"
                     "soilMoisture7Max           FLOAT,"
                     "soilMoisture7MaxTime       TIME,"
                     "soilMoisture7Avg           FLOAT,"
                     "soilMoisture8Min           FLOAT,"
                     "soilMoisture8MinTime       TIME,"
                     "soilMoisture8Max           FLOAT,"
                     "soilMoisture8MaxTime       TIME,"
                     "soilMoisture8Avg           FLOAT,"
                     "leafTemperature1Min           FLOAT,"
                     "leafTemperature1MinTime       TIME,"
                     "leafTemperature1Max           FLOAT,"
                     "leafTemperature1MaxTime       TIME,"
                     "leafTemperature1Avg           FLOAT,"
                     "leafTemperature2Min           FLOAT,"
                     "leafTemperature2MinTime       TIME,"
                     "leafTemperature2Max           FLOAT,"
                     "leafTemperature2MaxTime       TIME,"
                     "leafTemperature2Avg           FLOAT,"
                     "leafTemperature3Min           FLOAT,"
                     "leafTemperature3MinTime       TIME,"
                     "leafTemperature3Max           FLOAT,"
                     "leafTemperature3MaxTime       TIME,"
                     "leafTemperature3Avg           FLOAT,"
                     "leafTemperature4Min           FLOAT,"
                     "leafTemperature4MinTime       TIME,"
                     "leafTemperature4Max           FLOAT,"
                     "leafTemperature4MaxTime       TIME,"
                     "leafTemperature4Avg           FLOAT,"
                     "leafTemperature5Min           FLOAT,"
                     "leafTemperature5MinTime       TIME,"
                     "leafTemperature5Max           FLOAT,"
                     "leafTemperature5MaxTime       TIME,"
                     "leafTemperature5Avg           FLOAT,"
                     "leafTemperature6Min           FLOAT,"
                     "leafTemperature6MinTime       TIME,"
                     "leafTemperature6Max           FLOAT,"
                     "leafTemperature6MaxTime       TIME,"
                     "leafTemperature6Avg           FLOAT,"
                     "leafTemperature7Min           FLOAT,"
                     "leafTemperature7MinTime       TIME,"
                     "leafTemperature7Max           FLOAT,"
                     "leafTemperature7MaxTime       TIME,"
                     "leafTemperature7Avg           FLOAT,"
                     "leafTemperature8Min           FLOAT,"
                     "leafTemperature8MinTime       TIME,"
                     "leafTemperature8Max           FLOAT,"
                     "leafTemperature8MaxTime       TIME,"
                     "leafTemperature8Avg           FLOAT,"
                     "leafWetness1Min           FLOAT,"
                     "leafWetness1MinTime       TIME,"
                     "leafWetness1Max           FLOAT,"
                     "leafWetness1MaxTime       TIME,"
                     "leafWetness1Avg           FLOAT,"
                     "leafWetness2Min           FLOAT,"
                     "leafWetness2MinTime       TIME,"
                     "leafWetness2Max           FLOAT,"
                     "leafWetness2MaxTime       TIME,"
                     "leafWetness2Avg           FLOAT,"
                     "leafWetness3Min           FLOAT,"
                     "leafWetness3MinTime       TIME,"
                     "leafWetness3Max           FLOAT,"
                     "leafWetness3MaxTime       TIME,"
                     "leafWetness3Avg           FLOAT,"
                     "leafWetness4Min           FLOAT,"
                     "leafWetness4MinTime       TIME,"
                     "leafWetness4Max           FLOAT,"
                     "leafWetness4MaxTime       TIME,"
                     "leafWetness4Avg           FLOAT,"
                     "leafWetness5Min           FLOAT,"
                     "leafWetness5MinTime       TIME,"
                     "leafWetness5Max           FLOAT,"
                     "leafWetness5MaxTime       TIME,"
                     "leafWetness5Avg           FLOAT,"
                     "leafWetness6Min           FLOAT,"
                     "leafWetness6MinTime       TIME,"
                     "leafWetness6Max           FLOAT,"
                     "leafWetness6MaxTime       TIME,"
                     "leafWetness6Avg           FLOAT,"
                     "leafWetness7Min           FLOAT,"
                     "leafWetness7MinTime       TIME,"
                     "leafWetness7Max           FLOAT,"
                     "leafWetness7MaxTime       TIME,"
                     "leafWetness7Avg           FLOAT,"
                     "leafWetness8Min           FLOAT,"
                     "leafWetness8MinTime       TIME,"
                     "leafWetness8Max           FLOAT,"
                     "leafWetness8MaxTime       TIME,"
                     "leafWetness8Avg           FLOAT,"
                     "summaryType               ENUM" // 0 = daily, 1 = daytime, 2 = nighttime
                     ");";

const char *update1to2 = "alter table dailyObs ADD COLUMN heatIndex FLOAT;"
                   "alter table dailyObs ADD COLUMN humidex FLOAT;"
                   "alter table dailyObs ADD COLUMN windChill FLOAT;"

                   "alter table hourlySummary ADD COLUMN heatIndexMin FLOAT;"
                   "alter table hourlySummary ADD COLUMN heatIndexMinTime FLOAT;"
                   "alter table hourlySummary ADD COLUMN heatIndexMax FLOAT;"
                   "alter table hourlySummary ADD COLUMN heatIndexMaxTime FLOAT;"
                   "alter table hourlySummary ADD COLUMN heatIndexAvg FLOAT;"
                   "alter table hourlySummary ADD COLUMN humidexMin FLOAT;"
                   "alter table hourlySummary ADD COLUMN humidexMinTime FLOAT;"
                   "alter table hourlySummary ADD COLUMN humidexMax FLOAT;"
                   "alter table hourlySummary ADD COLUMN humidexMaxTime FLOAT;"
                   "alter table hourlySummary ADD COLUMN humidexAvg FLOAT;"
                   "alter table hourlySummary ADD COLUMN windChillMin FLOAT;"
                   "alter table hourlySummary ADD COLUMN windChillMinTime FLOAT;"
                   "alter table hourlySummary ADD COLUMN windChillMax FLOAT;"
                   "alter table hourlySummary ADD COLUMN windChillMaxTime FLOAT;"
                   "alter table hourlySummary ADD COLUMN windChillAvg FLOAT;"

                   "alter table dailySummary ADD COLUMN heatIndexMin FLOAT;"
                   "alter table dailySummary ADD COLUMN heatIndexMinTime FLOAT;"
                   "alter table dailySummary ADD COLUMN heatIndexMax FLOAT;"
                   "alter table dailySummary ADD COLUMN heatIndexMaxTime FLOAT;"
                   "alter table dailySummary ADD COLUMN heatIndexAvg FLOAT;"
                   "alter table dailySummary ADD COLUMN humidexMin FLOAT;"
                   "alter table dailySummary ADD COLUMN humidexMinTime FLOAT;"
                   "alter table dailySummary ADD COLUMN humidexMax FLOAT;"
                   "alter table dailySummary ADD COLUMN humidexMaxTime FLOAT;"
                   "alter table dailySummary ADD COLUMN humidexAvg FLOAT;"
                   "alter table dailySummary ADD COLUMN windChillMin FLOAT;"
                   "alter table dailySummary ADD COLUMN windChillMinTime FLOAT;"
                   "alter table dailySummary ADD COLUMN windChillMax FLOAT;"
                   "alter table dailySummary ADD COLUMN windChillMaxTime FLOAT;"
                   "alter table dailySummary ADD COLUMN windChillAvg FLOAT;"
                   
                   "update schema set version = 2;"
                   "VACUUM";


const char *update2to3 = "alter table dailyObs ADD COLUMN apparentTemp FLOAT;"
                   "alter table dailyObs ADD COLUMN cloudHeight FLOAT;"

                   "alter table hourlySummary ADD COLUMN apparentTempMin FLOAT;"
                   "alter table hourlySummary ADD COLUMN apparentTempMinTime FLOAT;"
                   "alter table hourlySummary ADD COLUMN apparentTempMax FLOAT;"
                   "alter table hourlySummary ADD COLUMN apparentTempMaxTime FLOAT;"
                   "alter table hourlySummary ADD COLUMN apparentTempAvg FLOAT;"
                   "alter table hourlySummary ADD COLUMN cloudHeightMin FLOAT;"
                   "alter table hourlySummary ADD COLUMN cloudHeightMinTime FLOAT;"
                   "alter table hourlySummary ADD COLUMN cloudHeightMax FLOAT;"
                   "alter table hourlySummary ADD COLUMN cloudHeightMaxTime FLOAT;"
                   "alter table hourlySummary ADD COLUMN cloudHeightAvg FLOAT;"

                   "alter table dailySummary ADD COLUMN apparentTempMin FLOAT;"
                   "alter table dailySummary ADD COLUMN apparentTempMinTime FLOAT;"
                   "alter table dailySummary ADD COLUMN apparentTempMax FLOAT;"
                   "alter table dailySummary ADD COLUMN apparentTempMaxTime FLOAT;"
                   "alter table dailySummary ADD COLUMN apparentTempAvg FLOAT;"
                   "alter table dailySummary ADD COLUMN cloudHeightMin FLOAT;"
                   "alter table dailySummary ADD COLUMN cloudHeightMinTime FLOAT;"
                   "alter table dailySummary ADD COLUMN cloudHeightMax FLOAT;"
                   "alter table dailySummary ADD COLUMN cloudHeightMaxTime FLOAT;"
                   "alter table dailySummary ADD COLUMN cloudHeightAvg FLOAT;"

                   "update schema set version = 3;"
                   "VACUUM";

const char *update3to4 = "alter table dailyObs ADD COLUMN windGustDir FLOAT;"
                   "alter table hourlySummary ADD COLUMN windGustDirAvg FLOAT;"
                   "alter table dailySummary ADD COLUMN windGustDirAvg FLOAT;"
                   "update schema set version = 4;"
                   "VACUUM";

const char *update4to5 = "create table windData  ( time INTEGEER PRIMARY KEY,"
                   "speed FLOAT,"
                   "dirSin FLOAT,"
                   "dirCos FLOAT);"
                   "update schema set version = 5;"
                   "VACUUM";
                   
const char *update5to6 = "create table rainData  ( time INTEGEER PRIMARY KEY,"
                   "amount FLOAT);"
                   "update schema set version = 6;"
                   "VACUUM";

const char *update6to7 =
               "alter table dailyObs ADD COLUMN rain24Hour FLOAT;"

               "alter table hourlySummary ADD COLUMN rain24HourMin FLOAT;"
               "alter table hourlySummary ADD COLUMN rain24HourMinTime TIME;"
               "alter table hourlySummary ADD COLUMN rain24HourMax FLOAT;"
               "alter table hourlySummary ADD COLUMN rain24HourMaxTime TIME;"
               "alter table hourlySummary ADD COLUMN rain24HourAvg  FLOAT;"

               "alter table dailySummary ADD COLUMN rain24HourMin FLOAT;"
               "alter table dailySummary ADD COLUMN rain24HourMinTime TIME;"
               "alter table dailySummary ADD COLUMN rain24HourMax FLOAT;"
               "alter table dailySummary ADD COLUMN rain24HourMaxTime TIME;"
               "alter table dailySummary ADD COLUMN rain24HourAvg  FLOAT;"
               "update schema set version = 7;"
               "VACUUM";

const char *update7to8 =
               "alter table dailySummary ADD COLUMN summaryType ENUM;"
               "update schema set version = 8;"
               "update dailySummary set summaryType = 0;"
               "VACUUM";

const char *update8to9 = 
               "alter table dailyObs ADD COLUMN instantRain FLOAT;"

               "alter table hourlySummary ADD COLUMN instantRainMax FLOAT;"
               "alter table hourlySummary ADD COLUMN instantRainMaxTime TIME;"
               "alter table dailySummary ADD COLUMN instantRainMax FLOAT;"
               "alter table dailySummary ADD COLUMN instantRainMaxTime TIME;"
               "update schema set version = 9;"
               "VACUUM";
